//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoiNYC.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class E {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal E() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoiNYC.Domain.Resources.E", typeof(E).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string BannerLocation_Homepage {
            get {
                return ResourceManager.GetString("BannerLocation_Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Page.
        /// </summary>
        public static string BannerLocation_ListPage {
            get {
                return ResourceManager.GetString("BannerLocation_ListPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        public static string HorizontalAllignment_Center {
            get {
                return ResourceManager.GetString("HorizontalAllignment_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string HorizontalAllignment_Left {
            get {
                return ResourceManager.GetString("HorizontalAllignment_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string HorizontalAllignment_Right {
            get {
                return ResourceManager.GetString("HorizontalAllignment_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate.
        /// </summary>
        public static string InvoiceType_Corporate {
            get {
                return ResourceManager.GetString("InvoiceType_Corporate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual.
        /// </summary>
        public static string InvoiceType_Personal {
            get {
                return ResourceManager.GetString("InvoiceType_Personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Menu.
        /// </summary>
        public static string Menu_Category {
            get {
                return ResourceManager.GetString("Menu_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Menu.
        /// </summary>
        public static string Menu_Collection {
            get {
                return ResourceManager.GetString("Menu_Collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu_Menu {
            get {
                return ResourceManager.GetString("Menu_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Menu.
        /// </summary>
        public static string Menu_SubMenu {
            get {
                return ResourceManager.GetString("Menu_SubMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basket.
        /// </summary>
        public static string OrderStatus_Basket {
            get {
                return ResourceManager.GetString("OrderStatus_Basket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string OrderStatus_Cancelled {
            get {
                return ResourceManager.GetString("OrderStatus_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed.
        /// </summary>
        public static string OrderStatus_Confirmed {
            get {
                return ResourceManager.GetString("OrderStatus_Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered.
        /// </summary>
        public static string OrderStatus_Delivered {
            get {
                return ResourceManager.GetString("OrderStatus_Delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipped.
        /// </summary>
        public static string OrderStatus_Shipped {
            get {
                return ResourceManager.GetString("OrderStatus_Shipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting Confirmation.
        /// </summary>
        public static string OrderStatus_WaitingConfirmation {
            get {
                return ResourceManager.GetString("OrderStatus_WaitingConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed.
        /// </summary>
        public static string PaymentStatus_Confirmed {
            get {
                return ResourceManager.GetString("PaymentStatus_Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string PaymentStatus_Error {
            get {
                return ResourceManager.GetString("PaymentStatus_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string PaymentStatus_Pending {
            get {
                return ResourceManager.GetString("PaymentStatus_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Void.
        /// </summary>
        public static string PaymentStatus_Void {
            get {
                return ResourceManager.GetString("PaymentStatus_Void", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string ShowcaseType_Category {
            get {
                return ResourceManager.GetString("ShowcaseType_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection.
        /// </summary>
        public static string ShowcaseType_Collection {
            get {
                return ResourceManager.GetString("ShowcaseType_Collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string ShowcaseType_Product {
            get {
                return ResourceManager.GetString("ShowcaseType_Product", resourceCulture);
            }
        }
    }
}
